# Site settings
title: Beautiful Burmese Typography
email: kayhzaw@gmail.com
description: >
  Beautiful Burmese Typography
baseurl: "/beautiful-burmese-type/" # the subpath of your site, e.g. /blog/
twitter_username: khzaw
github_username:  khzaw

# Build settings
markdown: kramdown
